### ISSUE TITLE
完成 2D 正齒輪繪圖系統

### ISSUE THREAD

**Issue by 40223148** [40223148/2015cda_g5#3]

**Comment by 40223148** [comment]
使用者利用瀏覽器連結至各組的 2D 正齒輪繪圖系統, 系統提供齒數, 模數與壓力角等3個欄位, 使用者根據使用說明, 填入所需設計參數後送出表單, 系統繪出符合規格之 2D 正齒輪輪廓圖.

**Comment by 40223148** [comment]
這裡將 2D 繪圖分成:
1. 表單
2. Brython 繪圖
3. 手繪開線正齒輪
4. 統整雲端程式與電子書報告編寫規畫
等四項工作.

1-2人將 1.表單 以及 2.Brython繪圖在近端做整合
2人完成手繪見開線正齒輪(理論) 可以上網搜尋  先繪成紙本 只後做成電子檔會更好

**Comment by 40223148** [comment]
這個全球資訊網上的 2D 繪圖, 之前在程式語言二課程中已經練習過, 當時利用 Brython  程式庫進行互動式的台灣國旗, 日本國旗與美國國旗的繪圖, 而且具有參數互動的設計, 應該可以套用當時的程式碼 https://github.com/coursemdetw/2014c2 , 當時的 html 與 pdf 檔案轉換採用 pandoc, 應該也可以用來轉換 Gitbook 所產生的 .md 檔案

**Comment by 40223144** [comment]
我 1

**Comment by 40223144** [comment]
手繪正齒輪還要做成電子檔?什麼意思?

**Comment by 40223148** [comment]
就是把寫成紙本的內容整理成電子檔  這樣的話如果以後還需要用到就不用再做一份了  直接可以用你做好的電子檔下去講解

**Comment by 2014c2g3** [comment]
我要手繪開線正齒輪，有人要跟我一起嗎?

**Comment by 402231466** [comment]
我4

**Comment by 40223144** [comment]
我也可以手繪正齒輪

**Comment by 40223125** [comment]
表單要幹嘛?

**Comment by 40223148** [comment]
自己上網查詢老師的影片就會知道了

**Comment by 40223125** [comment]
查無此影片  之  中午吃啥

**Comment by 40223148** [comment]
影片請去http://192.168.1.181:8000

**Comment by 40223125** [comment]
1

**Comment by 2014c2g3** [comment]
ㄟㄟㄟㄟㄟ
我們要開始做了!!!!!!!!!!!!!!

**Comment by 2014c2g23** [comment]
2有缺嗎
